package com.artspace.appuser.outgoing;

import io.quarkus.hibernate.reactive.panache.PanacheRepository;
import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
class FailureRepository implements PanacheRepository<FailedMessage> {
  // This class will be automatically generated by quarkus engine
}
